apiVersion: v1
kind: Service
metadata:
  name: image-api-service
spec:
  selector:
    app: detector # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # The port you'll use in the browser
      targetPort: 8000 # The port your FastAPI app is listening on
  type: LoadBalancer   # This tells AWS to give you a public URL/IP